Based on the provided JSON pipeline, here is the converted Tekton YAML pipeline:

```yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: node-app-pipeline
spec:
  params:
    - name: NODE_HOME
      description: "Node installation directory"
      default: "/usr/local/node"
  tasks:
    - name: checkout
      params:
        - name: url
          description: "Repository URL to clone"
          default: "https://github.com/your-repository/node-app.git"
      taskSpec:
        steps:
          - name: git-clone
            image: tekton/git-clone
            script: |
              #!/bin/bash
              echo "Cloning the repository"
              git clone $(params.url)
    - name: build
      taskSpec:
        steps:
          - name: npm-install
            image: node
            workingDir: /workspace/source
            script: |
              #!/bin/bash
              echo "Installing dependencies"
              npm install
    - name: test
      taskSpec:
        steps:
          - name: npm-test
            image: node
            workingDir: /workspace/source
            script: |
              #!/bin/bash
              echo "Running tests"
              npm test
    - name: deploy
      taskSpec:
        steps:
          - name: npm-deploy
            image: node
            workingDir: /workspace/source
            script: |
              #!/bin/bash
              echo "Deploying to staging environment"
              npm run deploy:staging
    - name: cleanup
      taskSpec:
        steps:
          - name: cleanup-resources
            image: ubuntu
            script: |
              #!/bin/bash
              echo "Cleaning up resources..."
  finally:
    - name: pipeline-completed
      taskSpec:
        steps:
          - name: echo-completed
            image: ubuntu
            script: |
              #!/bin/bash
              echo "Pipeline completed!"
    - name: deployment-status
      taskSpec:
        steps:
          - name: echo-deployment-status
            image: ubuntu
            script: |
              #!/bin/bash
              echo "Deployment to staging successful!"
      when:
        success: "true"
    - name: pipeline-failed
      taskSpec:
        steps:
          - name: echo-failure
            image: ubuntu
            script: |
              #!/bin/bash
              echo "Pipeline failed! Check the logs for errors."
      when:
        failure: "true"
```

This YAML defines a Tekton Pipeline that includes tasks for checking out the repository, building, testing, deploying, and cleanup. It also includes final tasks for completion, success, and failure messages based on the pipeline outcome.