```yaml
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: node-app-pipeline
spec:
  tasks:
    - name: checkout-task
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/your-repository/node-app.git
    - name: build-task
      taskRef:
        name: build-task
    - name: test-task
      taskRef:
        name: test-task
    - name: deploy-task
      taskRef:
        name: deploy-task
    - name: cleanup-task
      taskRef:
        name: cleanup-task
  finally:
    tasks:
      - name: pipeline-completed-task
        taskRef:
          name: echo-task
        params:
          - name: message
            value: "Pipeline completed!"
    success:
      - name: deployment-successful-task
        taskRef:
          name: echo-task
        params:
          - name: message
            value: "Deployment to staging successful!"
    failure:
      - name: pipeline-failed-task
        taskRef:
          name: echo-task
        params:
          - name: message
            value: "Pipeline failed! Check the logs for errors!"

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
  steps:
    - name: git-clone-step
      image: alpine/git
      script: |
        git clone $(params.url)

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-task
spec:
  steps:
    - name: npm-install-step
      image: node
      script: |
        npm install

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-task
spec:
  steps:
    - name: npm-test-step
      image: node
      script: |
        npm test

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-task
spec:
  steps:
    - name: deploy-staging-step
      image: node
      script: |
        npm run deploy:staging

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-task
spec:
  steps:
    - name: cleanup-step
      image: alpine
      script: |
        echo "Cleaning up resources!"

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: echo-task
spec:
  steps:
    - name: echo-step
      image: alpine
      script: |
        echo "$(params.message)"
```