apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: node-app-pipeline
spec:
  tasks:
    - name: checkout-task
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/your-repository/node-app.git
      results:
        - name: source
          path: /workspace/git-clone-output
    - name: build-task
      taskRef:
        name: build
      runAfter:
        - checkout-task
    - name: test-task
      taskRef:
        name: test
      runAfter:
        - build-task
    - name: deploy-task
      taskRef:
        name: deploy
      runAfter:
        - test-task
    - name: cleanup-task
      taskRef:
        name: cleanup
      runAfter:
        - deploy-task
  finally:
    tasks:
      - name: pipeline-completed-task
        taskRef:
          name: echo
        params:
          - name: message
            value: "Pipeline completed!"
        runAfter:
          - cleanup-task
    success:
      - name: deployment-successful-task
        taskRef:
          name: echo
        params:
          - name: message
            value: "Deployment to staging successful!"
        runAfter:
          - pipeline-completed-task
    failure:
      - name: pipeline-failed-task
        taskRef:
          name: echo
        params:
          - name: message
            value: "Pipeline failed! Check the logs for errors!"
        runAfter:
          - pipeline-completed-task

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
  steps:
    - name: git-clone-step
      image: alpine/git
      script: |
        git clone $(params.url) /workspace/git-clone-output

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build
spec:
  steps:
    - name: npm-install-step
      image: node
      script: |
        cd /workspace/git-clone-output
        npm install

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test
spec:
  steps:
    - name: npm-test-step
      image: node
      script: |
        cd /workspace/git-clone-output
        npm test

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy
spec:
  steps:
    - name: deploy-staging-step
      image: node
      script: |
        cd /workspace/git-clone-output
        npm run deploy:staging

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup-step
      image: alpine
      script: |
        echo "Cleaning up resources!"
