apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: checkout-task
spec:
  workspaces: []
  params: []
  steps:
    - name: git-clone
      image: alpine/git
      env:
        - name: NODE_HOME
          value: /usr/local/node
      script: |
        git clone https://github.com/your-repository/node-app.git
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-task
spec:
  workspaces: []
  params: []
  steps:
    - name: npm-install
      image: node
      env:
        - name: NODE_HOME
          value: /usr/local/node
      script: |
        npm install
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-task
spec:
  workspaces: []
  params: []
  steps:
    - name: npm-test
      image: node
      env:
        - name: NODE_HOME
          value: /usr/local/node
      script: |
        npm test
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deploy-task
spec:
  workspaces: []
  params: []
  steps:
    - name: deploy-to-staging
      image: node
      env:
        - name: NODE_HOME
          value: /usr/local/node
      script: |
        npm run deploy:staging
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: cleanup-task
spec:
  workspaces: []
  params: []
  steps:
    - name: cleanup-resources
      image: busybox
      script: |
        echo 'Cleaning up resources...'
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: node-app-pipeline
spec:
  workspaces: []
  tasks:
    - name: checkout
      taskRef:
        name: checkout-task
    - name: build
      taskRef:
        name: build-task
    - name: test
      taskRef:
        name: test-task
    - name: deploy
      taskRef:
        name: deploy-task
    - name: cleanup
      taskRef:
        name: cleanup-task
    - name: pipeline-completed
      taskRef:
        name: pipeline-completed-task
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pipeline-completed-task
spec:
  workspaces: []
  params: []
  steps:
    - name: pipeline-completed
      image: busybox
      script: |
        echo 'Pipeline completed!'
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: deployment-success-task
spec:
  workspaces: []
  params: []
  steps:
    - name: deployment-success
      image: busybox
      script: |
        echo 'Deployment to staging successful!'
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: pipeline-failure-task
spec:
  workspaces: []
  params: []
  steps:
    - name: pipeline-failure
      image: busybox
      script: |
        echo 'Pipeline failed! Check the logs for errors.'
